### ISSUE TITLE
The site is putting a false resolution for what it actually is 

### ISSUE THREAD

**Issue by emadseed** [jakehilborn/debbit#103]
![image](https://github.com/jakehilborn/debbit/assets/122543277/d2fc7dc5-b296-43db-bf84-896c929f82f6)
It says its 1080p but in reality its only 720 It has been happening ever since I started using movie-web 8 or so months ago maybe a little longer, sometimes it is extremely worse and unwatchable
Could you guys please fix it, Thanks

**Comment by jakehilborn** [comment]
Wrong project, debbit doesn't do anything video related
