### ISSUE TITLE
MacOS ;; Selenium crashes before it even begins, even on fresh install, or after downgrading selenium to 4.2.0. 

### ISSUE THREAD

**Issue by arooni** [jakehilborn/debbit#104]
```
[I]  ~/b/debbit_v3  ./debbit
INFO: 2023-12-25 15:12:48,570        __     __    __    _ __
INFO: 2023-12-25 15:12:48,570   ____/ /__  / /_  / /_  (_) /_
INFO: 2023-12-25 15:12:48,570  / __  / _ \/ __ \/ __ \/ / __/
INFO: 2023-12-25 15:12:48,571 / /_/ /  __/ /_/ / /_/ / / /_
INFO: 2023-12-25 15:12:48,571 \__,_/\___/_.___/_.___/_/\__/  v2.1.4
INFO: 2023-12-25 15:12:48,571
INFO: 2023-12-25 15:12:48,867 No purchases yet complete for December 2023
INFO: 2023-12-25 15:12:48,867
INFO: 2023-12-25 15:12:48,872 Now bursting 2 example_card_description_example_merchant purchases
debbit.py:509: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
debbit.py:516: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
debbit.py:516: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object
debbit.py:516: DeprecationWarning: service_log_path has been deprecated, please pass in a Service object
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "debbit.py", line 113, in burst_loop
  File "debbit.py", line 289, in web_automation_wrapper
  File "debbit.py", line 516, in get_webdriver
  File "selenium/webdriver/firefox/webdriver.py", line 179, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 268, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 359, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 424, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 247, in check_response
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status signal


```
I have tried to downgrade selenium from 4.16.0 to 4.2.0; yet it seems to have no effect.  

Thinking I messed up the config.txt file, I downloaded the latest release from this repo, then ran the debbit executable.  Same error.  

This was working prior, maybe its my Mac's version? 13.5.2.  What's weird is even after I uninstall all pip packages of selenium and it's the same error.

**Comment by arooni** [comment]
Apparently it doesn't matter which version of selenium you have installed.

 it's linked to the executable geckodriver which I've tried rolling back to earlier versions via https://github.com/mozilla/geckodriver/releases without luck.  

Has anyone been able to get this working recently?  

If so, which version of geckodriver did you use?

**Comment by joshjohanning** [comment]
Good theory @arooni on the `geckodriver`. I was able to get it to work with `v0.34.0` on my macOS m1 

https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-macos.tar.gz

**Comment by ghost** [comment]
> Good theory @arooni on the `geckodriver`. I was able to get it to work with `v0.34.0` on my macOS m1
> 
> https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-macos.tar.gz

I can confirm this version of geckodriver as a fix for me as well. Thanks!
Just open the linked tar and replace the existing geckodriver file at: debbit/program_files/ folder.

**Comment by arooni** [comment]
That 0.34.0 version of geckodriver fixed everything.  Thanks so much!  Closing this issue for now.
