### ISSUE TITLE
att_bill_pay does not login

### ISSUE THREAD

**Issue by jakehilborn** [jakehilborn/debbit#30]
I've gotten a few reports about att_bill_pay login not working. I'm currently looking into fixing it.

Here is a patch for Windows that I'm testing. 
[debbit-v2.0.2-dev-att-patch-win64.zip](https://github.com/jakehilborn/debbit/files/4871962/debbit-v2.0.2-dev-att-patch-win64.zip)

This branch contains some in-progress code with the fixes: https://github.com/jakehilborn/debbit/tree/fix_att_bill_pay

**Comment by Agile-Travel** [comment]
Thank you so much for this amazing solutions!
