### ISSUE TITLE
Preferred approach for implementing multi-card per merchant support?

### ISSUE THREAD

**Issue by kevin-david** [jakehilborn/debbit#4]
Nice script! I'm considering implementing multi-card support - as in, I want to make 20 purchases on Amazon over two cards, 10 purchases on each. 

Obviously I could accomplish this with multiple "instances" of the application, but it seemed nice to be able for each merchant to "rotate" through cards.

The approach I was going to take would be to make `card` a multi-value option rather than a single-value one, then round-robin through cards in the order they're supplied to reach `total_purchases` - does this seem reasonable? 

I can think of more complicated approaches involving randomly switching between cards, # of purchases per card, etc. - but this seemed the simplest. Any thoughts?

**Comment by jakehilborn** [comment]
I've gotten requests from some users to support differing numbers of transactions per card. One user has four cards which need 60, 60, 15, and 15 transactions respectively.

This is a complicated change to make. I'm also looking at redesigning the config system in general to separate out merchant by merchant. Another user just wrote a module for AT&T which now brings the monolith config file to 4 merchants. It's getting long and hard to read through in a text editor.

How about I handle this change? I've got the whole day open so I was planning on working on debbit anyway. 🙂

**Comment by kevin-david** [comment]
Nice - that's why I checked, I'll hold off!

> I'm also looking at redesigning the config system in general to separate out merchant by merchant.

That'd be really cool. I've got the auto-archive thing I alluded to over in #3 working, but it uses this hacky approach (the `dry_run` feature was something else I was playing with):

```
--- a/src/sample_config.txt
+++ b/src/sample_config.txt
@@ -11,6 +11,10 @@ amazon_gift_card_reload:
     # change this to True after configuring the options below
     enabled: False
 
+    merchant_specific_config:
+        # Set to true to automatically archive the latest gift card reload
+        archive: True
+
     # Set this to true to skip the actual GC-reload - useful for testing
     dry_run: False
 ```

**Comment by rowdawg21** [comment]
Has the multi-card per merchant feature been implemented yet?  I'm not seeing it, but I'm new to this site so I may not be looking in the right place.  I have 3 debit cards that I put 10-12 Amazon reload transactions on every month, and it would be great to get it automated!

**Comment by kevin-david** [comment]
Given this is implemented now, closing!
