### ISSUE TITLE
Debbit v.2.1 thread error

### ISSUE THREAD

**Issue by Mai-d-o** [jakehilborn/debbit#46]
Running into this thread error using debbit 2.1

I have two Amazon reloads. The first one goes through but not the second one.

Thanks in advance!

![image](https://user-images.githubusercontent.com/72676708/106478133-883fe100-646e-11eb-814e-e7a7b8256550.png)

**Comment by jakehilborn** [comment]
Can you post your `config.txt`? Remove your username, password, and card number of course. I have a feeling that your amount_min and amount_max are the same and Windows is handling this situation weird.

**Comment by Mai-d-o** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/72676708/106492988-31420800-647e-11eb-8839-2c3cc45d6d47.png)

**Comment by Mai-d-o** [comment]
I found out why, the amount_min/max for one of the payment has decimals, should have been in integers of cents.
