### ISSUE TITLE
Amazon gift card page changed

### ISSUE THREAD

**Issue by jamesgol** [jakehilborn/debbit#59]
I think amazon changed their page today.  I can share my failure files, but I suspect it'll be obvious.

```
  File "debbit.py", line 294, in web_automation_wrapper
    result = merchant.web_automation(driver, merchant, amount)
  File "/home/webdriver/debbit/program_files/merchants/amazon_gift_card_reload.py", line 141, in web_automation
    WebDriverWait(driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, 'asv-manual-reload-amount')))
  File "/home/webdriver/.local/share/virtualenvs/debbit-CQa1CbFm/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

```

```
  File "debbit.py", line 294, in web_automation_wrapper
    result = merchant.web_automation(driver, merchant, amount)
  File "/home/webdriver/debbit/program_files/merchants/amazon_gift_card_reload.py", line 24, in web_automation
    expected_conditions.element_to_be_clickable((By.XPATH, "//button[starts-with(text(),'Reload')]"))
  File "/home/webdriver/.local/share/virtualenvs/debbit-CQa1CbFm/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by jakehilborn** [comment]
Are you still seeing this error? Amazon gift card reloads are still working for me. Sometimes there are transient website issues that go away. Each purchase has up to 5 retries so letting debbit run and allow retries often does the trick.

**Comment by jamesgol** [comment]
That's so weird, I wonder if amazon was doing some A/B testing on my account for a bit.  After a few days of failures I just disabled it and finished out the month manually.  It looks like it's working now and when I manually visit the amazon gift card reload page it looks back the way it was.

**Comment by jamesgol** [comment]
Here is the page/product that amazon was going to for reload for me.  https://www.amazon.com/gp/product/B086KKT3RX

All bad reviews of people complaining about the gift card reload changing, some earlier in the month but others around the same time mine changed.

I'll close this out, but I wonder if this is a change everyone will see in the future.  I spent a bit working on some changes to make it work but it started to get non-trivial and I didn't have time to properly troubleshoot it.
