### ISSUE TITLE
Support scheduling purchases every x number of months

### ISSUE THREAD

**Issue by shbach** [jakehilborn/debbit#73]
The way debbit is currently designed, cards added will always have at least one purchase done a month. Is it possible to have an option to have purchases occur ever x number of months? e.g.  every 3 months or 6 months

The reason I request this is that I have a fairly large number of credit cards I want to keep active but having all of them have a monthly purchase is too much, especially when most of them don't have a small balance fee waiver. At most I would like to have one purchase every three months or even every six months on the cards.

**Comment by jakehilborn** [comment]
Debbit's core design, configuration, and scheduler are built for monthly transactions. It would be quite a lot of work to do this so I'm not planning on it.
