### ISSUE TITLE
Amazon Anti-automation challenge

### ISSUE THREAD

**Issue by minideezel** [jakehilborn/debbit#9]
Trying to get this to work on Amazon, but it keeps running into an anti-automation challenge when trying to log in. See failures attached.
[AntiAutomationFailure.zip](https://github.com/jakehilborn/debbit/files/4499843/AntiAutomationFailure.zip)

**Comment by jakehilborn** [comment]
Are you using a VPN or a different network than you would normally log in with?

This can also happen if you try running debbit too many times in a row.

**Comment by minideezel** [comment]
Nope, normal network. I got it the first time I ran debbit I think. It definitely didn't do any transactions before I was getting that. I had just changed my password and added a phone number to Amazon tho. I'll try to run it again later.

**Comment by jakehilborn** [comment]
I intend to add the code to handle the anti-automation challenge.

Also, I've got an in-progress branch that keeps the debbit Firefox window open for multiple purchases. This should help prevent this issue since Amazon won't think it's a new browser logging into your account every time.

**Comment by Marksman79** [comment]
> Also, I've got an in-progress branch that keeps the debbit Firefox window open for multiple purchases. This should help prevent this issue since Amazon won't think it's a new browser logging into your account every time.

Is "close_browser: no" in yet?

**Comment by jakehilborn** [comment]
@Marksman79 Yes but only if you download and run the source code. I'm trying to get the next release out soon, but it might be a couple weeks.

If you download the latest code on the master branch you can use it now. I deleted the "close_browser: no" feature and replaced it with a different solution that uses cookies. Instructions for the current code on the master branch are found at http://jakehilborn.github.io/debbit

**Comment by Marksman79** [comment]
Much thanks for the status update! I'm more than happy to wait until the full release -- take your time :)

**Comment by jakehilborn** [comment]
@Marksman79 Debbit 2.0 has been [released](https://github.com/jakehilborn/debbit/releases) which supports cookie persistence. This should prevent the anti-automation challenges causing failures.

**Comment by minideezel** [comment]
v2.0 Worked perfectly, had the automation challenge and was able to enter the code and the OTP and then press enter in Debbit and it proceeded with no problem!
